language: ruby
sudo: false
cache: bundler
env:
  global: NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
branches:
  only:
    - master
script: bundle exec rake
notifications:
  email:
    on_success: never
    on_failure: always
